import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import "dotenv/config";
import Nav from "@/components/Nav";
import Progress from "@/components/Progress";
import Contact from "@/components/Contact";
import { Suspense } from "react";

const cairo = Cairo({
  subsets: ["arabic"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "Alsahm Advertising",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cairo.variable} font-sans`}>
      <body>
        <Suspense fallback={<h1>Loading...</h1>}>
          <Nav />
          <Progress />

          <Contact />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
