import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "dotenv/config";
import Nav from "@/components/Nav";
import Progress from "@/components/Progress";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alsahm Advertising",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Nav />
        <Progress />

        <Contact />
        {children}
      </body>
    </html>
  );
}
